---
  .travis.yml:
    hc_secure: "AuL9F35isOjsxHHyfASWSs/IjjaE/UL4K5z7fXLNwG3VkGTtS9hRa38Giemu\\n5avM7PwHywiOCAc61xsJIuwQUiwL4ezfyUk0FwDxsp/AOeQp8imh7mZLBCxK\\nebxnQzmULI73TJwhYBPX7E8Z4mShpghta6CUzErbIu551UCb2rE="

